[package]
name = "poly_phy"
version = "0.1.0"
authors = ["Seldom"]
edition = "2018"

[dependencies]
cairo-rs = "0.8.1"

[dependencies.gtk]
version = "0.8.0"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]
